### ISSUE TITLE
Consider updating to splncs04nat

### ISSUE THREAD

**Issue by k4rtik** [latextemplates/LNCS#35]
See https://github.com/tpavlic/splncs04nat

**Comment by koppor** [comment]
Sounds good!

Just some notes:

- The current file is from http://phaseportrait.blogspot.com/2011/02/natbib-compatible-bibtex-style-bst-file.html - and was not updated since then.
- Fun fact: The commit adding the .bst file was authored by the owner of the linked repository (https://github.com/latextemplates/LNCS/commit/f7a0e535eea9bbb6c8412e42699d443a38fa0033).

**Comment by k4rtik** [comment]
It seems like @tpavlic set up the github repo I linked a few months (Feb vs Aug 2018) after their PR here.
